### ISSUE TITLE
Phase missing Decloak

### ISSUE THREAD

**Issue by brianries** [brianries/xwingduel#2]
I know it's not in the core set, but we might want to add the 'decloak' phase placeholder before activation, just to future proof the logic.

**Comment by aetheriac** [comment]
I was lumping that into the pre-reveal step

**Comment by brianries** [comment]
Doesn't decloak require its own separate iteration of lowest to highest pilot skill?  Then do the Activation iteration?

**Comment by aetheriac** [comment]
Probably
